import type { QuizQuestion } from "./types";

export const REQUIREMENTS_DIAGNOSIS_STORAGE_KEY = "requirements-diagnosis.quiz.v2";
export const REQUIREMENTS_DIAGNOSIS_RESULT_KEY = "requirements-diagnosis.result.v2";

export const quizQuestions: QuizQuestion[] = [
  {
    id: "q1",
    section: "经营画像",
    dimension: "商业视野：深耕 ↔ 拓展",
    prompt: "行业突然冒出风口，所有人都在冲。你第一反应是？",
    type: "single",
    options: [
      { value: "A", label: "先按兵不动，把现有业务守稳、数据看清" },
      { value: "B", label: "会关注机会，但只拿少量资源观察和验证" },
      { value: "C", label: "先判断它和现有业务的关系，再决定节奏" },
      { value: "D", label: "会尽快做一个小切口，看看能不能抢到先机" },
      { value: "E", label: "先上车，有位置才有机会形成话语权" },
    ],
  },
  {
    id: "q2",
    section: "经营画像",
    dimension: "商业视野：深耕 ↔ 拓展",
    prompt: "如果只能选一种成功路径，你更认可哪一种？",
    type: "single",
    options: [
      { value: "A", label: "一个领域做到前 10%，持续加深壁垒" },
      { value: "B", label: "先把一个领域做稳，再谨慎拓展相邻机会" },
      { value: "C", label: "先做深基本盘，再看有没有第二曲线" },
      { value: "D", label: "同时布局几个相邻方向，哪个跑出来就加码" },
      { value: "E", label: "三个领域各做到前 30%，用组合机会放大增长" },
    ],
  },
  {
    id: "q14",
    section: "经营画像",
    dimension: "商业视野：深耕 ↔ 拓展",
    prompt: "当你看到一个新业务机会时，最先会问自己什么？",
    type: "single",
    options: [
      { value: "A", label: "它会不会分散我当前最重要的主线" },
      { value: "B", label: "它能不能服务现有客户和已有能力" },
      { value: "C", label: "它和当前业务的协同、风险、机会各是什么" },
      { value: "D", label: "能不能用很小成本先验证市场反应" },
      { value: "E", label: "如果不试，会不会错过下一轮增长窗口" },
    ],
  },
  {
    id: "q3",
    section: "经营画像",
    dimension: "判断方式：经验判断 ↔ 数据验证",
    prompt: "业绩突然涨了 30%，但不确定是策略对还是市场好。你第一反应是？",
    type: "single",
    options: [
      { value: "A", label: "结果说明方向大概率对了，先延续当前打法" },
      { value: "B", label: "先凭经验判断主因，再补一些关键数据确认" },
      { value: "C", label: "经验和数据都要看，先拆出几个可能原因" },
      { value: "D", label: "必须拆清楚哪些因素可复制，再决定加码" },
      { value: "E", label: "没有数据闭环就不能算策略成功，先做归因分析" },
    ],
  },
  {
    id: "q15",
    section: "经营画像",
    dimension: "判断方式：经验判断 ↔ 数据验证",
    prompt: "团队对一个方案争论不下时，你通常怎么拍板？",
    type: "single",
    options: [
      { value: "A", label: "我会相信自己对客户和市场的直觉" },
      { value: "B", label: "经验判断先行，但会听取关键反对意见" },
      { value: "C", label: "先做小范围验证，再结合经验判断" },
      { value: "D", label: "先明确指标和样本，用数据减少争论" },
      { value: "E", label: "没有验证数据前，不轻易做大投入决策" },
    ],
  },
  {
    id: "q16",
    section: "经营画像",
    dimension: "判断方式：经验判断 ↔ 数据验证",
    prompt: "面对一个你没做过的新项目，你更依赖什么来降低不确定性？",
    type: "single",
    options: [
      { value: "A", label: "过往商业经验和对人的判断" },
      { value: "B", label: "找做过的人聊一圈，形成经验判断" },
      { value: "C", label: "一边访谈一边看数据，快速形成判断" },
      { value: "D", label: "先设验证指标，用小样本跑出信号" },
      { value: "E", label: "先建立数据口径和验证模型，再推进" },
    ],
  },
  {
    id: "q4",
    section: "经营画像",
    dimension: "组织落地：系统重构 ↔ 快速试水",
    prompt: "两种创业者，你更接近哪种风格？",
    type: "single",
    options: [
      { value: "A", label: "花三年打磨产品，一推出就惊艳" },
      { value: "B", label: "先把底层能力和流程打扎实，再逐步上线" },
      { value: "C", label: "快速出 MVP，验证对了再回头精雕细琢" },
      { value: "D", label: "三个月出第一版，边卖边改" },
      { value: "E", label: "先跑起来，哪怕粗糙，也要尽快拿到真实反馈" },
    ],
  },
  {
    id: "q13",
    section: "经营画像",
    dimension: "组织落地：系统重构 ↔ 快速试水",
    prompt: "如果一个 AI 试点跑通了，你更倾向怎么让团队真正用起来？",
    type: "single",
    options: [
      { value: "A", label: "重写流程、角色和考核方式，让它变成固定能力" },
      { value: "B", label: "先沉淀标准流程和培训材料，再逐步推广" },
      { value: "C", label: "先形成一套可复制做法，再决定推广范围" },
      { value: "D", label: "先让小团队继续用，边用边改，成熟后扩大" },
      { value: "E", label: "先快速扩散给更多人用，用真实反馈倒逼优化" },
    ],
  },
  {
    id: "q17",
    section: "经营画像",
    dimension: "组织落地：系统重构 ↔ 快速试水",
    prompt: "当一个流程效率很低时，你通常怎么改？",
    type: "single",
    options: [
      { value: "A", label: "先重新设计流程、职责和标准，再让团队执行" },
      { value: "B", label: "先梳理关键节点，修掉最影响效率的结构问题" },
      { value: "C", label: "先找一个环节试改，确认有效后再规范化" },
      { value: "D", label: "先换工具或方法跑一版，看哪里立刻见效" },
      { value: "E", label: "先行动，边跑边修，比等完整方案更重要" },
    ],
  },
  {
    id: "q5",
    section: "经营画像",
    dimension: "投入心智：成本优先 ↔ 长期投入",
    prompt: "如果要在公司里落地 AI，你更愿意怎么投入？",
    type: "single",
    options: [
      { value: "A", label: "先找明确省人省钱的环节，算清回报再投入" },
      { value: "B", label: "先小预算试点，看到回报再逐步增加投入" },
      { value: "C", label: "短期回报和长期能力都要兼顾" },
      { value: "D", label: "愿意先投入知识库、模板、自动化工作台等基础能力" },
      { value: "E", label: "只要方向确定，可以接受阶段性投入建设长期能力" },
    ],
  },
  {
    id: "q18",
    section: "经营画像",
    dimension: "投入心智：成本优先 ↔ 长期投入",
    prompt: "你判断一个 AI 项目值不值得做，最看重什么？",
    type: "single",
    options: [
      { value: "A", label: "短期能节省多少人力、时间或现金成本" },
      { value: "B", label: "三个月内能不能看到可量化改善" },
      { value: "C", label: "既要有短期收益，也要能沉淀方法" },
      { value: "D", label: "能不能形成可复用能力，长期摊薄成本" },
      { value: "E", label: "能不能成为未来业务增长和组织升级的基础设施" },
    ],
  },
  {
    id: "q19",
    section: "经营画像",
    dimension: "投入心智：成本优先 ↔ 长期投入",
    prompt: "如果 AI 试点前两周效果不明显，你会怎么处理？",
    type: "single",
    options: [
      { value: "A", label: "先暂停，避免继续投入看不到回报的成本" },
      { value: "B", label: "缩小投入，要求更快看到明确结果" },
      { value: "C", label: "复盘问题，再决定是否继续" },
      { value: "D", label: "如果方向对，会继续优化数据、流程和使用习惯" },
      { value: "E", label: "愿意给它一个建设周期，因为能力沉淀需要时间" },
    ],
  },
  {
    id: "q6",
    section: "经营画像",
    dimension: "风险策略：风险防守 ↔ 创新进攻",
    prompt: "AI 试点有不确定性，你更倾向怎么启动？",
    type: "single",
    options: [
      { value: "A", label: "先选低风险、低影响环节，权限和边界清楚再试" },
      { value: "B", label: "先建立评估清单和退出标准，再决定试点范围" },
      { value: "C", label: "控制风险，但也保留探索空间" },
      { value: "D", label: "只要方向有机会，先做一个小试点快速验证" },
      { value: "E", label: "先抢机会，风险在推进中动态控制" },
    ],
  },
  {
    id: "q7",
    section: "经营画像",
    dimension: "风险策略：风险防守 ↔ 创新进攻",
    prompt: "如果第一个 AI 试点效果一般，你会怎么处理？",
    type: "single",
    options: [
      { value: "A", label: "先暂停扩大，复盘投入产出和风险" },
      { value: "B", label: "保留有效部分，缩小范围继续观察" },
      { value: "C", label: "判断问题出在场景、工具还是执行，再决定" },
      { value: "D", label: "调整场景或流程，尽快换一个切入点继续试" },
      { value: "E", label: "继续快速试错，失败样本也是找到机会的成本" },
    ],
  },
  {
    id: "q20",
    section: "经营画像",
    dimension: "风险策略：风险防守 ↔ 创新进攻",
    prompt: "面对一个可能带来增长、但团队没做过的 AI 项目，你会怎么安排？",
    type: "single",
    options: [
      { value: "A", label: "没有清晰边界和责任人前，不启动" },
      { value: "B", label: "先做风险清单，限定范围后小心推进" },
      { value: "C", label: "先定义可接受风险，再做试点" },
      { value: "D", label: "给小团队授权，让他们快速验证机会" },
      { value: "E", label: "把它当成创新突破口，愿意承担试错成本" },
    ],
  },
  {
    id: "q21",
    section: "AI 落地画像",
    dimension: "AI 态度与心理准备度",
    prompt: "你现在对 AI 进入自己业务的态度，更接近哪一种？",
    type: "single",
    options: [
      { value: "A", label: "还在观望，担心投入后看不到实际效果" },
      { value: "B", label: "有兴趣，但需要先看懂具体案例和边界" },
      { value: "C", label: "已经尝试过，想知道哪些场景更值得继续" },
      { value: "D", label: "认可价值，想把它更系统地放进工作流程" },
      { value: "E", label: "已经把 AI 当成接下来业务升级的关键变量" },
    ],
  },
  {
    id: "q8",
    section: "AI 落地画像",
    dimension: "AI 关注偏好",
    prompt: "你最关注 AI 的哪个方向？",
    type: "single",
    options: [
      { value: "A", label: "AI 前沿技术资讯：新模型、新能力、新突破" },
      { value: "B", label: "AI 落地商业结果和变现模式：别讲技术，告诉我结果" },
      { value: "C", label: "AI 高效学习成长路径：我想上手，想知道从哪开始" },
    ],
  },
  {
    id: "q9",
    section: "AI 落地画像",
    dimension: "日均 AI 工作使用时长",
    prompt: "你现在每天把 AI 实际用于工作处理的时间大概是？",
    type: "single",
    options: [
      { value: "A", label: "几乎没有把 AI 用进日常工作" },
      { value: "B", label: "1-2 小时" },
      { value: "C", label: "2-4 小时" },
      { value: "D", label: "4 小时以上" },
    ],
  },
  {
    id: "q10",
    section: "AI 落地画像",
    dimension: "已常态化使用的 AI 工具",
    prompt: "下面哪些 AI 工具已经进入你的日常工作？",
    type: "multiple",
    options: [
      { value: "A", label: "AI 聊天工具：豆包、千问、元宝、DeepSeek、ChatGPT、Gemini 等" },
      { value: "B", label: "低代码 AI 搭建工具：Coze、Dify、n8n 等" },
      { value: "C", label: "专业代码类 AI 工具：Cursor、Claude Code、Codex 等" },
      { value: "D", label: "专业 Agent 工具：OpenClaw、Hermes、Workbuddy、QoderWork、CoWork 等" },
      { value: "E", label: "还没有任何 AI 工具进入日常工作" },
    ],
  },
  {
    id: "q22",
    section: "AI 落地画像",
    dimension: "AI 是否进入真实工作流",
    prompt: "AI 现在和你的真实工作流关系如何？",
    type: "single",
    options: [
      { value: "A", label: "基本没有进入工作流，只是偶尔了解" },
      { value: "B", label: "个人临时使用，主要用来提效某些小任务" },
      { value: "C", label: "已经固定用于一个明确场景，比如内容、客服或资料整理" },
      { value: "D", label: "多个场景已经有固定用法，但还没形成系统闭环" },
      { value: "E", label: "已经进入团队协作或业务流程，开始影响交付方式" },
    ],
  },
  {
    id: "q11",
    section: "AI 落地画像",
    dimension: "AI 认知宽度",
    prompt: "你觉得 AI 目前能帮你做以下哪些事？",
    type: "multiple",
    options: [
      { value: "A", label: "替我干活：写方案、回消息、整理资料、看邮件" },
      { value: "B", label: "替我创作：写小红书、做视频脚本、设计海报" },
      { value: "C", label: "替我分析：市场调研、竞品分析、数据整理" },
      { value: "D", label: "替我服务：客服回复、私域运营、社群管理" },
      { value: "E", label: "替我管理：订单管理、库存跟踪、排期调度" },
      { value: "F", label: "替我决策：商业方向、产品选择、定价策略" },
    ],
  },
  {
    id: "q12",
    section: "AI 落地画像",
    dimension: "AI 刚需诉求",
    prompt: "你当下最想让 AI 直接解决哪类工作难题？",
    type: "single",
    options: [
      { value: "A", label: "重复执行：通用方案、批量对账、自动回复、表格规整" },
      { value: "B", label: "内容创意：爆款笔记、短视频脚本、口播文案、宣传素材" },
      { value: "C", label: "客户转化：客服回复、线索跟进、私域运营、销售话术" },
      { value: "D", label: "经营分析：市场调研、竞品分析、数据整理、复盘报告" },
      { value: "E", label: "复杂流程：订单管理、内部 SOP、跨部门工作流、自动化闭环" },
    ],
  },
  {
    id: "q23",
    section: "AI 落地画像",
    dimension: "AI 落地方式偏好",
    prompt: "如果要真正把 AI 用起来，你更希望怎么落地？",
    type: "single",
    options: [
      { value: "A", label: "先学会工具，自己能独立上手" },
      { value: "B", label: "先套用成熟模板和案例，降低试错成本" },
      { value: "C", label: "先做一个小流程自动化，跑通后再扩大" },
      { value: "D", label: "希望团队一起导入，形成统一方法和流程" },
      { value: "E", label: "希望有人帮我定制方案，直接对接业务结果" },
    ],
  },
  {
    id: "q24",
    section: "AI 落地画像",
    dimension: "AI 落地主要阻力",
    prompt: "如果现在推进 AI 落地，最大的阻力可能是什么？",
    type: "single",
    options: [
      { value: "A", label: "不知道从哪个业务场景开始" },
      { value: "B", label: "缺少工具方法，不知道怎么稳定做出来" },
      { value: "C", label: "现有数据、流程或 SOP 比较混乱" },
      { value: "D", label: "团队接受度和执行习惯可能跟不上" },
      { value: "E", label: "担心预算、ROI 或投入产出不清晰" },
    ],
  },
];
