services:
  nextjs:
    image: splice-ai-cn-shanghai.cr.volces.com/splice-ai/agent-team-nextjs:latest
    container_name: agent-team-nextjs
    restart: always
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - AUTH_COOKIE_SECURE=false

networks:
  app-network:
    external: true
