import type { AgentManifest } from "./types";

export const AGENTS: AgentManifest[] = [
  {
    id: "requirements-diagnosis",
    name: "需求诊断 Agent",
    route: "/requirements-diagnosis",
    category: "diagnosis",
    description: "通过多轮问卷式对话收集用户信息，完成需求分析与诊断。",
    version: "0.1.0",
    starterPrompts: [
      "帮我基于诊断结果做一份企业 AI 转型路线图。",
      "我想知道当前业务最适合先用 AI 改造哪个环节。",
      "请结合我的诊断结果，帮我评估一个 AI 项目是否值得做。",
    ],
    tools: [
      "askUserChoice",
      "showCards",
      "showChart",
      "showComparison",
      "showChecklist",
      "showTimeline",
      "showScorecard",
      "showDataTable",
      "showFramework",
    ],
    externalTools: ["webSearch"],
    rendererProfile: "default",
    promptBuilder: "requirementsDiagnosis",
    memoryPolicy: { mode: "session" },
  },
  {
    id: "deep-diagnosis",
    name: "深度诊断 Agent",
    route: "/deep-diagnosis",
    category: "diagnosis",
    description: "通过深度 Agent 问答，围绕业务现场生成 AI 落地路径。",
    version: "0.1.0",
    starterPrompts: [
      "帮我定位最值得先做 AI 改造的业务环节。",
      "我想做一份本月可执行的 AI 落地路线图。",
      "请评估一个 AI 自动化项目的优先级和风险。",
    ],
    tools: [
      "askUserChoice",
      "showCards",
      "showChart",
      "showComparison",
      "showChecklist",
      "showTimeline",
      "showScorecard",
      "showDataTable",
      "showFramework",
    ],
    externalTools: ["webSearch", "publishHtmlReport"],
    rendererProfile: "default",
    promptBuilder: "deepDiagnosis",
    memoryPolicy: { mode: "session" },
  },
  {
    id: "treasure-hunt",
    name: "大喜",
    route: "/treasure/hunt",
    category: "surprise",
    description: "把心里的惊喜变成能照着做的寻宝活动方案包。",
    version: "1.0.0",
    starterPrompts: [
      "我想给对象策划一个生日惊喜。",
      "帮我设计一个亲子寻宝游戏。",
      "我想求婚，但不想太俗。",
      "约朋友聚会，别让大家各刷手机。",
    ],
    tools: [
      "askUserChoice",
      "showCards",
      "showComparison",
      "showChecklist",
      "showTimeline",
      "showScorecard",
      "showGiftList",
      "showWishCard",
      "showVideoScript",
    ],
    rendererProfile: "treasure-hunt",
    promptBuilder: "treasureHunt",
    memoryPolicy: { mode: "session" },
  },
];

export function getAgentById(agentId: string | undefined | null): AgentManifest | undefined {
  return AGENTS.find((agent) => agent.id === agentId);
}
